import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { savedCourses, removeCourse, startDeviceRound, type SavedCourse } from '../offline/courses';
import { previewBackup, restoreBackup } from '../offline/backup';
import type { DownloadedRound } from '../offline/storage';

function message(e:unknown) {return e instanceof Error?e.message:'Could not save on this device.';}
function today() {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function OfflineLibrary({userId}:{userId:number}) {
  const navigate=useNavigate();const [courses,setCourses]=useState<SavedCourse[]>([]);const [error,setError]=useState('');const [date,setDate]=useState(today);const [busy,setBusy]=useState(false);
  const refresh=useCallback(()=>{try{setCourses(savedCourses(userId));}catch(e){setError(message(e));}},[userId]);
  useEffect(()=>{refresh();window.addEventListener('storage',refresh);window.addEventListener('golf-offline-change',refresh);return()=>{window.removeEventListener('storage',refresh);window.removeEventListener('golf-offline-change',refresh);};},[refresh]);
  return <section className="panel space-y-4"><div><p className="eyebrow">Play without a connection</p><h2 className="mt-2 text-2xl">Downloaded courses</h2><p className="mt-2 text-sm text-slate-500">Each download keeps its original tees, pars, and ratings. Download again from the course page when you want the latest setup.</p></div>
    {!courses.length?<p className="text-sm text-slate-600">Open a course, choose your tees and holes, then download it here for future rounds.</p>:<><label className="block max-w-xs text-sm font-semibold">Round date<input type="date" className="field mt-2" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2">{courses.map(c=><article key={`${c.course.id}-${c.round.tee_set_id}-${c.round.nine}`} className="space-y-3 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">{c.course.name}</h3><p className="text-sm text-slate-600">{c.round.tee_name||'Score only'} · {c.round.hole_count===18?'18 holes':`${c.round.nine==='back'?'Back':'Front'} nine`}</p><p className="text-xs text-slate-500">Downloaded {new Date(c.savedAt).toLocaleDateString()}{c.round.course_rating===null?' · Unrated':''}</p><button className="btn-primary w-full min-h-12" disabled={busy} onClick={()=>{setBusy(true);setError('');try{const entry=startDeviceRound(userId,c,date);navigate(`/offline/${entry.round.id}`);}catch(e){setError(message(e));setBusy(false);}}}>Start round on device</button><button className="text-xs text-slate-500 underline" onClick={()=>{try{removeCourse(userId,c);}catch(e){setError(message(e));}}}>Remove course download</button></article>)}</div></>}
    {error&&<p role="alert" className="error-notice">{error}</p>}
  </section>;
}
export function RestoreDeviceBackup({userId}:{userId:number}) {
  const navigate=useNavigate();const [preview,setPreview]=useState<DownloadedRound|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  return <section className="panel space-y-4"><h2 className="text-xl">Restore a device backup</h2><p className="text-sm text-slate-600">Recover a scorecard exported from Offline rounds. Restoration keeps its saved scores and checks for server changes when syncing.</p><label className="block text-sm font-semibold">Device backup JSON<input className="field mt-2" type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];setPreview(null);setError('');if(!file)return;setBusy(true);try{if(file.size>1000000)throw new Error('Choose a backup smaller than 1 MB.');setPreview(previewBackup(await file.text(),userId));}catch(e){setError(message(e));}finally{setBusy(false);}}}/></label>
    {preview&&<div className="rounded-xl bg-slate-50 p-4 space-y-3"><h3 className="font-semibold">{preview.round.course_name||preview.course.name}</h3><p className="text-sm">{preview.round.date} · {preview.round.tee_name||'Score only'} · {preview.round.hole_count} holes</p><p className="text-xs text-slate-500">{preview.shots?.length??0} GPS shots · {Object.keys(preview.round.green_notes??{}).length} holes with green notes</p><p className="text-sm">{preview.round.holes.filter(h=>h.strokes!==null).length} holes scored · {preview.round.holes.reduce((n,h)=>n+(h.strokes??0),0)} strokes recorded</p><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">Hole</th><th>Strokes</th><th>Putts</th><th>Penalties</th></tr></thead><tbody>{preview.round.holes.map(h=><tr key={h.hole_number} className="border-t"><th className="p-2">{h.hole_number}</th><td>{h.strokes??'—'}</td><td>{h.putts??'—'}</td><td>{h.penalties}</td></tr>)}</tbody></table></div>{!preview.serverOrigin&&<p className="text-sm text-amber-800">This older backup does not identify its server. Restore it only if it was exported from this server and account.</p>}<button className="btn-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const restored=await restoreBackup(preview);navigate(`/offline/${restored.round.id}`);}catch(e){setError(message(e));}finally{setBusy(false);}}}>Restore this scorecard</button><button className="btn-secondary ml-2" disabled={busy} onClick={()=>setPreview(null)}>Cancel</button></div>}
    {error&&<p role="alert" className="error-notice">{error}</p>}
  </section>;
}
