"""add tees, ratings, stroke index and round stat columns

Revision ID: 291fc33fba04
Revises: f3a1c9b2d7e4
Create Date: 2026-09-03 23:17:30.523208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291fc33fba04'
down_revision: Union[str, Sequence[str], None] = 'f3a1c9b2d7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tee_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('yardage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tee_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tee_sets_course_id'), ['course_id'], unique=False)

    op.create_table('tee_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tee_set_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('course_rating', sa.Float(), nullable=False),
    sa.Column('slope_rating', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tee_set_id'], ['tee_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tee_set_id', 'scope', name='uq_tee_rating_scope')
    )
    with op.batch_alter_table('tee_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tee_ratings_tee_set_id'), ['tee_set_id'], unique=False)

    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stroke_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('round_holes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fairway_hit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('putts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('penalties', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tee_set_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hole_count', sa.Integer(), nullable=False, server_default='18'))
        batch_op.add_column(sa.Column('nine', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('course_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('slope_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_par', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_rounds_tee_set_id_tee_sets', 'tee_sets', ['tee_set_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rounds_tee_set_id_tee_sets', type_='foreignkey')
        batch_op.drop_column('course_par')
        batch_op.drop_column('slope_rating')
        batch_op.drop_column('course_rating')
        batch_op.drop_column('nine')
        batch_op.drop_column('hole_count')
        batch_op.drop_column('tee_set_id')

    with op.batch_alter_table('round_holes', schema=None) as batch_op:
        batch_op.drop_column('penalties')
        batch_op.drop_column('putts')
        batch_op.drop_column('fairway_hit')

    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.drop_column('stroke_index')

    with op.batch_alter_table('tee_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tee_ratings_tee_set_id'))

    op.drop_table('tee_ratings')
    with op.batch_alter_table('tee_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tee_sets_course_id'))

    op.drop_table('tee_sets')
    # ### end Alembic commands ###
