"""add rounds, round_holes; shots gain round_id/hole_number, session_id nullable

Revision ID: 91a84aef90c8
Revises: 94e6ce576ce3
Create Date: 2026-07-13 07:33:36.754464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a84aef90c8'
down_revision: Union[str, Sequence[str], None] = '94e6ce576ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_hole', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rounds_user_id'), ['user_id'], unique=False)

    op.create_table('round_holes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_holes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_holes_hole_id'), ['hole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_holes_round_id'), ['round_id'], unique=False)

    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hole_number', sa.Integer(), nullable=True))
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_shots_round_id'), ['round_id'], unique=False)
        batch_op.create_foreign_key('fk_shots_round_id_rounds', 'rounds', ['round_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shots_round_id_rounds', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shots_round_id'))
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('hole_number')
        batch_op.drop_column('round_id')

    with op.batch_alter_table('round_holes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_holes_round_id'))
        batch_op.drop_index(batch_op.f('ix_round_holes_hole_id'))

    op.drop_table('round_holes')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_user_id'))
        batch_op.drop_index(batch_op.f('ix_rounds_course_id'))

    op.drop_table('rounds')
    # ### end Alembic commands ###
