"""add Course and Hole tables

Revision ID: 94e6ce576ce3
Revises: 2a8a4de1b8d4
Create Date: 2026-07-12 17:59:15.870289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e6ce576ce3'
down_revision: Union[str, Sequence[str], None] = '2a8a4de1b8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('osm_id', sa.String(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_table('holes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('green_lat', sa.Float(), nullable=True),
    sa.Column('green_lng', sa.Float(), nullable=True),
    sa.Column('hazards', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holes_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holes_course_id'))

    op.drop_table('holes')
    op.drop_table('courses')
    # ### end Alembic commands ###
