import type { Hole } from '../../api/types';
import { distanceYards } from '../../geo';
import { unitLabel,yardsToDisplay,type Unit } from '../../units';
import type { usePosition } from './usePosition';
export function DistancePanel({hole,gps,unit,compact=false}:{compact?:boolean;hole:Hole|undefined;gps:ReturnType<typeof usePosition>;unit:Unit}) {
  const mapped=hole?.green_lat!=null&&hole.green_lng!=null;
  const distance=mapped&&gps.position&&gps.fresh?Math.round(yardsToDisplay(distanceYards(gps.position.lat,gps.position.lng,hole.green_lat!,hole.green_lng!),unit)):null;
  if(compact)return <section className="play-distance play-distance-compact" aria-label="Distance to green"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-emerald-100">Green center</p><span className="text-2xl font-semibold" aria-label="Distance">{distance??'—'}</span><span className="ml-2 text-xs">{unitLabel(unit)}</span></div>{mapped&&!gps.enabled?<button className="min-h-11 rounded-lg bg-lime-300 px-3 text-sm font-bold text-emerald-950" onClick={gps.enable}>Enable GPS</button>:<p className="max-w-48 text-right text-xs">{!mapped?'Green not mapped · scoring available':gps.fresh?`GPS ±${Math.round(yardsToDisplay((gps.position?.accuracy??0)/0.9144,unit))} ${unitLabel(unit)} · ${gps.age}s ago`:'Waiting for an accurate GPS fix'}</p>}</div>{gps.error&&<p role="status" className="mt-1 text-xs text-amber-200">{gps.error}</p>}</section>;
  if(!mapped)return <section className="play-distance" aria-label="Distance to green"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-200">Green center</p><span className="text-3xl font-semibold">—</span></div><p className="mt-2 text-sm font-semibold">Green location not mapped</p><p className="mt-1 text-xs leading-relaxed text-emerald-100">Keep scoring and tracking shots. Add this hole’s green coordinates in course setup to enable its distance.</p></section>;
  return <section className="play-distance" aria-label="Distance to green"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold uppercase tracking-[.18em] text-emerald-200">Green center</span><span className="rounded-full border border-white/20 px-3 py-1 text-xs">{gps.fresh?'GPS live':gps.enabled?'Finding location':'GPS ready'}</span></div><div className="relative py-5 text-center"><div className="play-target" aria-hidden="true"><span/><span/><span/></div><div className="relative"><span className="text-[5.5rem] font-semibold leading-none tracking-tighter sm:text-[7rem]" aria-label="Distance">{distance??'—'}</span><span className="ml-2 text-lg text-emerald-200">{unitLabel(unit)}</span><p className="mt-2 text-sm text-emerald-100">{!mapped?'Green location not mapped':!gps.enabled?'Turn on GPS for your distance':distance===null?'Waiting for a fresh, accurate location':'To the mapped center • straight-line distance'}</p></div></div><div className="border-t border-white/15 pt-3 text-center text-xs text-emerald-100">{gps.position?`GPS accuracy ±${Math.round(yardsToDisplay(gps.position.accuracy/0.9144,unit))} ${unitLabel(unit)} · updated ${gps.age}s ago`:'Distances use your downloaded course and work without the server.'}</div>{!gps.enabled&&<button className="mt-4 min-h-12 w-full rounded-xl bg-lime-300 px-4 font-bold text-emerald-950" onClick={gps.enable}>Enable GPS</button>}{gps.error&&<p className="mt-3 text-sm text-amber-200" role="status">{gps.error}</p>}{gps.enabled&&gps.position&&!gps.fresh&&!gps.error&&<p className="mt-3 text-sm text-amber-200">Location is old or too imprecise. Distance and shot capture will resume with a better fix.</p>}</section>;
}
