import { useEffect,useState } from 'react';
import type { GreenNote } from '../../api/types';
const empty:GreenNote={break_direction:'unknown',pace:'unknown',note:''};
export function GreenNotebook({value,onSave,draftKey}:{draftKey:string;value:GreenNote|undefined;onSave:(note:GreenNote)=>Promise<void>}) {
  const [note,setNote]=useState<GreenNote>(()=>{try{return JSON.parse(localStorage.getItem(draftKey)??'null')??value??empty;}catch{return value??empty;}});const [saved,setSaved]=useState(false);const [error,setError]=useState('');
  const [dirty,setDirty]=useState(()=>!!localStorage.getItem(draftKey));
  useEffect(()=>{if(!dirty)setNote(value??empty);},[value,dirty]);
  function edit(next:GreenNote){setNote(next);setSaved(false);setDirty(true);try{localStorage.setItem(draftKey,JSON.stringify(next));setError('');}catch{setError('Could not save this draft on your device. Keep this screen open.');}}
  return <section className="play-card space-y-5"><div><p className="play-eyebrow">Read it. Remember it.</p><h2 className="mt-1 text-xl font-semibold">Green notebook</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">Record what you see from your ball toward the cup. These are your observations, not a measured slope or predicted putting line.</p></div><label className="block text-sm font-semibold">Your read<select className="field mt-2" value={note.break_direction} onChange={e=>{edit({...note,break_direction:e.target.value as GreenNote['break_direction']});}}><option value="unknown">Not recorded</option><option value="left">Breaks left</option><option value="right">Breaks right</option><option value="straight">Looks straight</option></select></label><label className="block text-sm font-semibold">Pace<select className="field mt-2" value={note.pace} onChange={e=>{edit({...note,pace:e.target.value as GreenNote['pace']});}}><option value="unknown">Not recorded</option><option value="uphill">Uphill</option><option value="downhill">Downhill</option><option value="level">Level</option></select></label><label className="block text-sm font-semibold">Hole notes<textarea className="field mt-2" rows={3} maxLength={500} value={note.note} placeholder="Stay below the pin. Back tier runs away…" onChange={e=>{edit({...note,note:e.target.value});}}/></label><button className="btn-primary w-full min-h-12" onClick={async()=>{try{await onSave(note);localStorage.removeItem(draftKey);setDirty(false);setSaved(true);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not save notes.');}}}>Save green notes</button>{dirty&&<p className="text-xs text-amber-800">Draft kept on this device. Save green notes to include them in sync and backups.</p>}{saved&&<p role="status" className="text-sm text-emerald-800">Green notes saved on device.</p>}{error&&<p role="alert" className="error-notice">{error}</p>}<div className="rounded-xl bg-slate-50 p-4 text-xs leading-relaxed text-slate-500">Surveyed green contours are not available for this course. GPS center distance does not tell us the green’s slope or today’s cup location.</div></section>;
}
