import { useState } from 'react';
import type { Club } from '../../api/types';
import type { DeviceShot, DownloadedRound } from '../../offline/storage';
import { changeShot, orderedShots, resolveShot, shotDistance } from '../../offline/shotHistory';
import { yardsToDisplay, unitLabel, type Unit } from '../../units';
import { ShotEditor } from './ShotEditor';
import { ShotReplayMap } from './ShotReplayMap';

export function ShotTimeline({entry,hole,clubs,unit}:{entry:DownloadedRound;hole:number;clubs:Club[];unit:Unit}) {
  const shots=orderedShots(entry.shots??[],hole),removed=orderedShots(entry.shots??[],hole,true);
  const [selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<DeviceShot|null>(null),[error,setError]=useState('');
  const [choice,setChoice]=useState<{shot:DeviceShot;value:'device'|'server'}|null>(null);
  const index=Math.max(0,shots.findIndex(s=>s.clientId===selected)),current=shots[index];
  const distance=(s:DeviceShot)=>{const d=shotDistance(s);return d==null?'Distance not recorded':`${yardsToDisplay(d,unit)} ${unitLabel(unit)} total`;};
  async function action(fn:()=>Promise<unknown>) {try{await fn();setError('');}catch(e){setError(e instanceof Error?e.message:'Could not save this change.');}}
  function details(s:DeviceShot) {return `${s.clubLabel} · ${s.sequence==null?'Order unknown':`#${s.sequence}`} · ${s.startLie??'unknown'} → ${s.endLie??'unknown'} · ${distance(s)} · ${s.penalties??0} penalties${s.holedOut?' · holed out':''}${s.deleted?' · removed':''}`;}
  const duplicate=shots.some((s,i)=>s.sequence!=null&&shots.some((t,j)=>j!==i&&s.sequence===t.sequence));
  return <section className="play-card space-y-4" aria-label="Shot history and replay">
    <div><p className="play-eyebrow">Review the hole</p><h2 className="mt-1 text-xl font-semibold">Shot history &amp; replay</h2><p className="mt-2 text-sm text-slate-600">{shots.length} recorded shots · {shots.reduce((sum,s)=>sum+(s.penalties??0),0)} recorded penalty strokes. Scorecard: {entry.round.holes.find(h=>h.hole_number===hole)?.strokes??'not scored'}.</p></div>
    {!entry.shotHistoryCheckedAt&&<p className="text-xs text-amber-800">Server history has not been checked on this device. Connect and sync to retrieve shots from other devices.</p>}
    {duplicate&&<p className="text-sm text-amber-800">Some shots share a number. Edit their order before relying on the sequence.</p>}
    {shots.some(s=>s.sequence==null)&&<p className="text-xs text-slate-600">Some older shots have unknown order. Their positions and sequence are shown only when recorded.</p>}
    <ShotReplayMap shots={shots} selected={current?.clientId??null} hole={entry.course.holes.find(h=>h.number===hole)} onSelect={setSelected}/>
    {current&&<div className="rounded-xl bg-slate-50 p-3 space-y-3"><div className="flex items-center justify-between gap-2"><button className="btn-secondary" disabled={index===0} onClick={()=>setSelected(shots[index-1].clientId)}>Previous shot</button><span className="text-sm">{index+1} / {shots.length}</span><button className="btn-secondary" disabled={index===shots.length-1} onClick={()=>setSelected(shots[index+1].clientId)}>Next shot</button></div><p className="text-sm font-semibold">{details(current)}</p>{current.start&&current.end&&<p className="text-xs text-slate-600">Start accuracy: {current.start.accuracy==null?'unknown':`±${current.start.accuracy} m`} · End accuracy: {current.end.accuracy==null?'unknown':`±${current.end.accuracy} m`}{current.start.timestamp!=null?` · Captured ${new Date(current.start.timestamp).toLocaleString()}`:''}</p>}</div>}
    {!shots.length&&<p className="text-sm text-slate-600">No active shots recorded for this hole. You can keep scoring without tracking shots.</p>}
    <ol className="space-y-3">{shots.map(s=><li key={s.clientId} className="rounded-xl border border-slate-200 p-3 space-y-2"><button className="text-left text-sm font-semibold underline" onClick={()=>setSelected(s.clientId)}>{details(s)}</button><p className="text-xs text-slate-500">{s.synced?'Synced':s.conflict?'Needs conflict review':'Saved on device · waiting to sync'}</p><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={!!s.conflict} onClick={()=>setEditing(s)}>Edit shot {s.sequence??'unknown'}</button><button className="btn-secondary" disabled={!!s.conflict} onClick={()=>void action(()=>changeShot(entry.userId,entry.round.id,s,{deleted:true}))}>Remove shot {s.sequence??'unknown'}</button></div>{s.conflict&&<div className="rounded-xl bg-amber-50 p-3 space-y-3"><h3 className="font-semibold">Review shot conflict</h3><p className="text-sm">Device: {details(s)}</p><p className="text-sm">Server: {details(s.conflict)}</p><details><summary className="text-xs">Compare recorded positions</summary><pre className="mt-2 overflow-x-auto text-xs">{JSON.stringify({device:{start:s.start,end:s.end},server:{start:s.conflict.start,end:s.conflict.end}},null,2)}</pre></details><button className="btn-secondary" onClick={()=>setChoice({shot:s,value:'device'})}>Keep device shot</button><button className="btn-secondary" onClick={()=>setChoice({shot:s,value:'server'})}>Use server shot</button></div>}</li>)}</ol>
    {editing&&<ShotEditor key={editing.clientId} initial={editing} clubs={clubs} unit={unit} onCancel={()=>setEditing(null)} onSave={async shot=>{await changeShot(entry.userId,entry.round.id,editing,shot);setEditing(null);}}/>}
    {removed.length>0&&<details className="rounded-xl border border-slate-200 p-3"><summary className="font-semibold">Removed shots ({removed.length})</summary><ul className="mt-3 space-y-3">{removed.map(s=><li key={s.clientId} className="space-y-2"><p className="text-sm">{details(s)}</p>{s.conflict?<div className="space-y-2"><p className="text-sm">Server: {details(s.conflict)}</p><button className="btn-secondary" onClick={()=>setChoice({shot:s,value:'device'})}>Keep removal</button><button className="btn-secondary" onClick={()=>setChoice({shot:s,value:'server'})}>Use server shot</button></div>:<button className="btn-secondary" onClick={()=>void action(()=>changeShot(entry.userId,entry.round.id,s,{deleted:false}))}>Restore shot {s.sequence??'unknown'}</button>}</li>)}</ul></details>}
    {choice&&<div className="rounded-xl bg-amber-50 p-4 space-y-3"><p>Use the reviewed {choice.value==='device'?'device':'server'} version of this shot?</p><button className="btn-primary" onClick={()=>void action(async()=>{await resolveShot(entry.userId,entry.round.id,choice.shot,choice.value);setChoice(null);})}>Confirm shot choice</button><button className="btn-secondary ml-2" onClick={()=>setChoice(null)}>Cancel</button></div>}
    {error&&<p role="alert" className="error-notice">{error}</p>}
    <p className="text-xs text-slate-500">Removed shots stay recoverable and are excluded from club statistics after synchronization. Shot edits never change your scorecard automatically.</p>
  </section>;
}
